#!/usr/bin/env python3
"""
Generate an unofficial RSS feed for James Lileks' "The Bleat"
(https://lileks.com/bleats/), which has no RSS feed of its own.

Run this on a schedule (cron / GitHub Actions), roughly once a day
after he usually posts. Each run:

  1. Fetches the Bleat's front page and figures out the URL of the
     current/latest post (the site uses an old-school redirect page
     rather than a predictable date-based URL, so a few detection
     strategies are tried in order).
  2. If that URL is new (not seen before), scrapes the post and adds
     it to a persistent feed history (state.json).
  3. Rewrites feed.xml with the most recent MAX_ITEMS entries.

Requirements:
    pip install requests beautifulsoup4

Usage:
    python generate_feed.py

State/output files (created alongside this script):
    state.json  - remembers which post URLs have already been added
    feed.xml    - the RSS feed itself; point your feed reader / host
                  a copy of this file wherever you want it served from
"""

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from email.utils import format_datetime
from xml.sax.saxutils import escape

import requests
from bs4 import BeautifulSoup

BASE_URL = "https://lileks.com/bleats/"
STATE_FILE = Path(__file__).parent / "state.json"
FEED_FILE = Path(__file__).parent / "feed.xml"
MAX_ITEMS = 30
USER_AGENT = "Mozilla/5.0 (compatible; BleatRSSBot/1.0; personal RSS generator)"

FEED_TITLE = "The Bleat (unofficial feed)"
FEED_LINK = BASE_URL
FEED_DESCRIPTION = (
    "Unofficial RSS feed for James Lileks' Bleat, generated by scraping "
    "lileks.com since the site doesn't publish one itself."
)


def get(url):
    r = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=20)
    r.raise_for_status()
    return r.text


def resolve_latest_url(index_html, base=BASE_URL):
    """The Bleat's index page redirects (via <meta refresh> or JS) to
    today's post. Try a few strategies to find that target URL, in
    order of reliability; fall back to treating the index page itself
    as the article if nothing else matches."""

    # 1) <meta http-equiv="refresh" content="0;url=...">
    m = re.search(
        r'http-equiv=["\']refresh["\'][^>]*content=["\'][^;]*;\s*url=([^"\'>]+)',
        index_html,
        re.I,
    )
    if m:
        return requests.compat.urljoin(base, m.group(1).strip())

    # 2) JS redirect: location.href = "..." or location = "..."
    m = re.search(r'location(?:\.href)?\s*=\s*["\']([^"\']+)["\']', index_html)
    if m:
        return requests.compat.urljoin(base, m.group(1).strip())

    # 3) A direct link to an /archive/.../....html-style page on the page
    soup = BeautifulSoup(index_html, "html.parser")
    a = soup.find("a", href=re.compile(r"/bleats/archive/\d+/\d+/\d+\.html"))
    if a:
        return requests.compat.urljoin(base, a["href"])

    # 4) Give up and assume the index page IS today's post
    return base


def scrape_post(url):
    html = get(url)
    soup = BeautifulSoup(html, "html.parser")

    for tag in soup.select("script, style, nav, footer, #disqus_thread, .disqus"):
        tag.decompose()

    title_tag = soup.find("title")
    title = title_tag.get_text(strip=True) if title_tag else url

    body = soup.find("body") or soup
    text = body.get_text(separator="\n", strip=True)
    lines = [l for l in text.split("\n") if l and "Disqus" not in l]
    description = "\n\n".join(lines[:40])  # cap length for feed readability

    return title, description


def load_state():
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {"seen": [], "items": []}


def save_state(state):
    STATE_FILE.write_text(json.dumps(state, indent=2))


def write_feed(items):
    now = format_datetime(datetime.now(timezone.utc))
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<rss version="2.0"><channel>',
        f"<title>{escape(FEED_TITLE)}</title>",
        f"<link>{escape(FEED_LINK)}</link>",
        f"<description>{escape(FEED_DESCRIPTION)}</description>",
        f"<lastBuildDate>{now}</lastBuildDate>",
    ]
    for item in items:
        parts.append("<item>")
        parts.append(f"<title>{escape(item['title'])}</title>")
        parts.append(f"<link>{escape(item['link'])}</link>")
        parts.append(f"<guid>{escape(item['link'])}</guid>")
        parts.append(f"<pubDate>{item['pubDate']}</pubDate>")
        parts.append(f"<description>{escape(item['description'])}</description>")
        parts.append("</item>")
    parts.append("</channel></rss>")
    FEED_FILE.write_text("\n".join(parts), encoding="utf-8")


def main():
    state = load_state()
    index_html = get(BASE_URL)
    latest_url = resolve_latest_url(index_html)

    if latest_url in state["seen"]:
        print(f"No new post. Latest known: {latest_url}")
        write_feed(state["items"])  # keep feed.xml present/fresh regardless
        return

    try:
        title, description = scrape_post(latest_url)
    except Exception as e:
        print(f"Failed to scrape {latest_url}: {e}", file=sys.stderr)
        sys.exit(1)

    new_item = {
        "title": title,
        "link": latest_url,
        "description": description,
        "pubDate": format_datetime(datetime.now(timezone.utc)),
    }

    state["seen"].append(latest_url)
    state["items"].insert(0, new_item)
    state["items"] = state["items"][:MAX_ITEMS]
    state["seen"] = state["seen"][-200:]  # don't let this grow forever

    save_state(state)
    write_feed(state["items"])
    print(f"Added new post: {title} -> {latest_url}")


if __name__ == "__main__":
    main()
